### PR TITLE
Add Location.search() method

### PR DESCRIPTION
**Pull request by easel**

### CODE REVIEW

**Comment by mysticfall** [comment]
Sorry for the very late response. Could you verify that the first parameter of the method is indeed optional?

I checked the documentation, but it looks like only the second parameter (`paramValue`) to be optional, which would make it unnecessary to add another method:

* https://docs.angularjs.org/api/ng/service/$location

**Comment by easel** [comment]
Angular docs leave something to be desired =[

From https://github.com/angular/angular.js/blob/v1.4.x/src/ng/location.js#L392 (and also the docs, just not the method definition line)

`   * @return {Object} If called with no arguments returns the parsed `search` object. If called with
   * one or more arguments returns `$location` object itself.`

**Comment by easel** [comment]
Really, the angular docs probably get across what's needed for a javascript developer, but they aren't sufficiently accurate for direct translation into a type system =/

**Comment by mysticfall** [comment]
I just checked the source code to confirm what you said and indeed you are right about it :)

I so much hate Javascript... grrrr....

**Comment by easel** [comment]
yeeep! Thanks for the merge.

**Pull request merged**
