### PR TITLE
Set State.params to Dictionary, add parent and resolve

### PR DESCRIPTION
**Pull request by easel**
- See https://github.com/angular-ui/ui-router/blob/a7d25c6/src/state.js#L581
- params is an dictionary that can be used to supply default values to url parameters

### CODE REVIEW

**Comment by mysticfall** [comment]
I could be wrong, but it seems that the [API documentation](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.$stateProvider) indicates that the `params` parameter expects a dictionary of string/boolean/function values which is not covered by the suggested signature of `js.Dictionary[UndefOr[String]]`(By the way, is there any difference between `UndefOr[String]` and `String`, when it's used as a type argument for `Dictionary`?)

And also, the documentation mentioned that the value of `parent` parameter could either be a string or an object, so I wonder it it should be `js.Object` rather than `String` in this case.

Please let me know what you think. Thanks!

**Comment by easel** [comment]
You're right, I think the correct type of the dictionary is probably js.Any. 

The reason I used UndefOr was to force the user to check if the value was actually set.

Not sure about parent, the ideal is probably actually a union of a State OR a string representing a state. Maybe another case for js.any?

**Comment by mysticfall** [comment]
It's one of the things that I really hate when writing a wrapper for a Javascript API. Using `Either` would look better in this case, but considering the fact that there are many similar instances in Angular API which involve more than two different types, I'm afraid we don't have many options if we want to preserve consistency.

As to `UndefOr`, I'm not too sure about placing such a restriction. While I agree with you that it would be much better if `js.Dictionary` can return optional types, so we don't accidentally fall into the undefined behavior trap, we are already provided implicit conversions between `js.Any` and `UndefOr` by default, which I'm afraid might make the restriction rather redundant, and easily circumventable.

**Comment by easel** [comment]
Yeah, I agree. I'm sorta learning as I go, trying to start replacing chunks of JS in an existing app with scala.js where I can. Very painful. I'll make some adjustments and re-push so you can take a look.

**Comment by mysticfall** [comment]
Same here :) Part of the reason why I've started this project was to get myself acquainted with both Scala and Angular.js, and I'm learning a lot now.

Thanks, and I'll merge it as soon as you make the adjustment.

**Comment by easel** [comment]
Ok I think we should be good-to-go, both are js.Any now. Realistically, angular is so heavily dependent on   it's string-based DI it's not surprising that almost everything ends up being js.Any.

**Comment by mysticfall** [comment]
Just merged the changes and published a new snapshot. Thanks again for the contribution!

**Comment by easel** [comment]
No problem, thanks for getting this started and keeping it moving.

**Pull request merged**
