### PR TITLE
Make interval and timeout more strongly typed

### PR DESCRIPTION
**Pull request by axos88**

### CODE REVIEW

**Comment by mysticfall** [comment]
I think it's a nice enhancement. The code looks good to me, except for the name of type parameter which rather stands out as we used `A` or `T` everywhere else.

Could you update the PR with the change if you don't object? Thanks for the contribution!

**Comment by axos88** [comment]
Patched, squashed, rebased, and PR updated

**Comment by mysticfall** [comment]
Just merged it and published a new snapshot. Thanks!

**Comment by axos88** [comment]
(y)

**Pull request merged**
