### PR TITLE
Fix usage of elements

### PR DESCRIPTION
**Pull request by svenwiegand**
Use HTML element whenever possible and respect that an Element in AngularJS is an `angular.element` which is effectively an array of DOM elements => Fix necessary to make Compile function work.

### CODE REVIEW

**Comment by mysticfall** [comment]
The proposed change with the link function looks good to me, but I'm not too sure about using `html.Element` instead of plain `Element`.

I don't think if too many people are using Angular.js to control any SVG content embeded in a HTML document. I haven't done it either but I believe it to be at least theoretically possible to do that and I'm building a quite complex SVG application currently, so I'm a bit reluctant to make it out of the without some assurance.

Is Angular.js designed specifically for dealing with HTML documents? And if not, what could be the benefits by limiting its usage for HTML?

**Comment by svenwiegand** [comment]
Okay, haven't even thought about SVG. My approach was to make usage as easy as possible and that would be accepting a standard `Element` as parameter everywhere and providing an `HTMLElement` as return type. But your SVG objection absolutely makes sense, so we should leave it as it is.

Regarding the element array-stuff: In the meanwhile I've made another -- more influencing change on my fork: I've changed `AngularElement` to derive from `org.scalajs.jquery.JQuery`. Deriving it from `Element` didn't work for me, as it isn't a simple DOM-element in reality. On the other hand this change requires an additional library dependency, but it makes using the lib so much easier, because in most cases what angular effectively provides *is* an `Angular.element` and because jQuery wraps the array of elements (which may also be empty) the code becomes cleaner as I don't need to work with `headOption` on the element arrays to handle the empty case.

Any thoughts from your side?

**Comment by mysticfall** [comment]
I like the idea. Before your suggestion, I didn't thought it would be a good approach because the reason why _Angular.js_ provides its own version of _JQuery_ is to make the dependency optional.

However, I realized that depending on `scalajs-jquery` doesn't really mandate one should include a standalone version of the JavaScript library, so now I'm fully supportive of the idea.

**Comment by svenwiegand** [comment]
The `Compile` stuff is strange, because the AngularJS-documentation does state that the `LinkFunction` receives a single element. Also trying to get back an `angular.element` does not work -- this one here is the only working solution.

**Comment by mysticfall** [comment]
I can confirm that the link function actually returns an array, not an element like the documentation claims. Currently, there's just one place in my current project where `$compile` is used, and as it turned out, I just passed the result to `jQuery.append` which also accept either an element or an array, so I didn't notice the problem until now. (Ah... I officially hate Javascript... especially when its documentation lies!)

I haven't checked the clone function yet, but I assume it should follow the case with the link function, as they are related to each other.

As to the problem with `angular.element` you mentioned, does it mean we need further tests before we could merge this PR? If so, could you let me know how to test this? Is it just a matter of trying to invoke some of the functions in `angular.element` on the returned element from the link function?

**Comment by svenwiegand** [comment]
I've also only tested the `$compile` function (appears in my unit tests to test directives) but not the link function. For `Angular.element` there is pull request #81. Don't see any issues here -- I think this can be merged without issues.

**Comment by mysticfall** [comment]
Just merged the changes and published a new snapshot. Thanks for the contribution!

**Pull request merged**
