### PR TITLE
Route builder

### PR DESCRIPTION
**Pull request by math85360**
Is it in the spirit of your post #38 ?

Simple RouteBuilder :
```
RouteBuilder()
  .controller("name of controller")
  .template("content here")
  .build()
```

### CODE REVIEW

**Comment by mysticfall** [comment]
Exactly :)

By the way, could you rebase it and remove the commented out parts (until the macros done)?

**Comment by math85360** [comment]
@mysticfall 
Is there a possibility to make a small macro project in the sbt with a dependency to macro paradise ?

I will study that to automatically discover all services (factory, controllers, config, ...) and to call automatically Angular.module.controller[A] ?

**Comment by math85360** [comment]
It's done ! :)

**Comment by mysticfall** [comment]
Thanks! I'll merge it right now.

By the way, does macro paradise support automatic discovery for annotated classes? It would be quite interesting if we could do that, but I'm afraid I'm not sure how exactly I could help you in experimenting this.

It's already a macro project, so I suppose creating a local branch with an additional dependency wouldn't be a too much hassle. If you need anything specific, please let me know.

By the way, I'm currently working on another project called [Scales](https://github.com/greencatsoft/scales) which also happens to use macro to register certain types of classes with an annotation.

Unlike this project, it has pretty comprehensive test cases, so it might be useful if you just need a small project to test macros.

**Comment by math85360** [comment]
The macro project will serve in an sbt task to discover annotated classes.

Next it will build an object with the Angular.module methods calls.

The macro project could also automatically generates Builder with a @withBuilder on Route it will generate class RouteBuilder like automatically for example.

I will look at this ! :)

**Comment by mysticfall** [comment]
Thanks for the explanation. I'm very much interested in this, so I'm looking forward to see some progress soon!

**Pull request merged**
