### PR TITLE
Add cases for optional $compile arguments

### PR DESCRIPTION
**Pull request by easel**

### CODE REVIEW

**Comment by mysticfall** [comment]
Could you provide me any reference (documentation, source location, examples, etc) which shows it's valid to pass a string value as the `tElement` argument, please?

I've looked up the documentation, but couldn't find any mention of valid types for the argument.

Sorry for the hassle.

[rant]Again, I officially hate dynamic languages![/rant]

**Comment by easel** [comment]
Yes, angular in particular is painful.

The docs for $compile are at https://docs.angularjs.org/api/ng/service/$compile, specifically the part you want is where it says this:

```
Usage
$compile(element, transclude, maxPriority);

Arguments
Param	Type	Details
element	stringDOMElement	
Element or HTML string to compile into a template function.

transclude	function(angular.Scope, cloneAttachFn=)	
function available to directives - DEPRECATED.

Note: Passing a transclude function to the $compile function is deprecated, as it e.g. will not use the right outer scope. Please pass the transclude function as a parentBoundTranscludeFn to the link function instead.
maxPriority	number	
only apply directives lower than given priority (Only effects the root element(s), not their children)

```

For some reason they don't have proper anchors on that page, but there are several examples where they call $compile with a single argument, which appears to be the most common usage especially given the second argument is deprecated.

**Comment by mysticfall** [comment]
Ah, I've totally missed that one... thanks for the clarification!

**Comment by easel** [comment]
As an aside, I may have just not noticed it, but it would probably be a good idea to specify what angular version the library is targeting. I'm assuming 1.3.x?

**Comment by mysticfall** [comment]
Actually, it's something I've been thinking about but haven't decided yet. As you assumed, it's mostly 1.3.x for now, but I'll be probably adding 1.4 features as needed.

I know it's not an ideal way to write a wrapper library, but so far, I've maintained this project mainly to be used for my own proprietary project, so I had to give priorities to which feature I needed at the moment, rather than to such efforts which would be needed to achieve the best compatibility with a specific version of Angular.js.

I hope things would get better, if more people start to contribute to the project. Maybe I should take sometime later to read the latest Angular document to review our current level of compatibility. But until then, I'm afraid I can only say that it's somewhere between 1.3.x and 1.4 for now.

**Comment by easel** [comment]
Well, you and I are in the same boat. I've got a fairly large proprietary angular app, but I'm fed up ... javascript ... so I'm starting to write more stuff in scalajs, hence the pull requests =p  Given the nature of the javascript ecosystem, I don't think theres another way to build such a facade. A lot of the functionality is not clearly documented so I think it's much better add functions as you use them as verification.

Perhaps the thing to do is to "officially" target 1.4 so there is a clear path to conflict resolution, but leave things 1.3.x compatible where it just works. Once of these days I'll swap out my angular to 1.4 and see what works, I don't think there are a huge number of breaking changes.

**Comment by mysticfall** [comment]
Yeah, I'm also fed up with Javascript, not just using it but as well as writing a wrapper around it, which is the reason why I recently started to make a pure Scala.js framework :)

By the way, there's already a ticket in the issue tracker for my other project for upgrading Angular.js to 1.4, on which I plan to start working soon. So, I'll see how well it goes and update the documentation then.

**Comment by easel** [comment]
I agree, a pure scalaJS framework is the way to go. I'm finding neither angular nor react is super friendly to bi-directional interop.

**Pull request merged**
